import Link from 'next/link'

export default function DevelopersPage() {
  return (
    <div className="prose prose-invert max-w-none">
      <h1>ARC for Developers</h1>
      <p className="text-xl italic text-muted-foreground mb-12">
        Building contemplative technology with local-first architecture
      </p>

      <hr className="my-12" />

      <h2>Core Development Principles</h2>

      <h3>Latency = Mindflow</h3>
      <p>Response time directly impacts the quality of thought. Fast enough to maintain flow, slow enough to allow reflection. Target: 200ms for local operations, graceful degradation for complex processing.</p>

      <h3>Minimal UI = Inner Calm</h3>
      <p>Interface design that reduces cognitive load rather than demanding attention. Every element serves contemplation, nothing serves engagement metrics.</p>

      <h3>Local Data = Self-Ownership</h3>
      <p>Users own their data, their insights, and their digital contemplative space. No surveillance, no data mining, no behavioral tracking.</p>

      <h3>Deterministic Prompts</h3>
      <p>Use JSON schemas to ensure consistent, reproducible interactions. Transparency in how inputs become outputs.</p>

      <hr className="my-12" />

      <h2>Architecture Overview</h2>
      <div className="bg-card/30 border border-border rounded-lg p-6 my-8">
        <pre className="text-sm text-muted-foreground">
{`User Input
    ↓
ARC-0 (Reflect) ←→ ARC-1 (Explore)
    ↓
Integrator
    ↓
✦ Spark → Local Storage → Export Formats`}
        </pre>
      </div>

      <h3>Message Contract</h3>
      <pre className="bg-background border border-border rounded-lg p-4 text-sm">
{`interface Message {
  role: 'arc0' | 'arc1' | 'user'
  content: string
  trace_id: string
  timestamp: number
  context?: Record<string, any>
}`}
      </pre>

      <h3>Spark Contract</h3>
      <pre className="bg-background border border-border rounded-lg p-4 text-sm">
{`interface Spark {
  summary: string
  evidence: string[]
  timestamp: number
  confidence: number
  tags: string[]
  export_formats: {
    markdown: string
    json: object
    plaintext: string
  }
}`}
      </pre>

      <hr className="my-12" />

      <h2>Local-First Development</h2>

      <h3>Privacy Architecture</h3>
      <pre className="bg-background border border-border rounded-lg p-4 text-sm overflow-x-auto">
{`// No telemetry by default
const TELEMETRY_ENABLED = false

class DataController {
  private localDB: SQLiteDB
  private encryptionKey: CryptoKey
  
  async storeLocal(data: any): Promise<void> {
    const encrypted = await encrypt(data, this.encryptionKey)
    await this.localDB.store(encrypted)
  }
  
  async exportUserData(): Promise<ExportBundle> {
    return {
      sparks: await this.getSparks(),
      conversations: await this.getConversations(),
      format_version: '1.0.0',
      license: 'User owns this data completely'
    }
  }
}`}
      </pre>

      <hr className="my-12" />

      <h2>Getting Started</h2>

      <h3>Development Environment</h3>
      <pre className="bg-background border border-border rounded-lg p-4 text-sm">
{`# Clone the runtime (coming soon)
git clone https://github.com/arc-project/runtime
cd runtime

# Install with privacy-first defaults
npm install --no-telemetry
npm run setup:local-first

# Configure local database
npm run db:init:encrypted`}
      </pre>

      <h3>Core API</h3>
      <pre className="bg-background border border-border rounded-lg p-4 text-sm">
{`// Initialize ARC runtime
const arc = new ARCRuntime({
  local_storage_path: './arc_data',
  encryption_enabled: true
})

// Process input through both minds
const dialogue = await arc.processInput(userInput)

// Generate spark from dialogue
const spark = await arc.integrateSpark(dialogue)

// Export user data
const exportBundle = await arc.exportUserData()`}
      </pre>

      <hr className="my-12" />

      <h2>Export Formats</h2>

      <h3>Markdown Export</h3>
      <pre className="bg-background border border-border rounded-lg p-4 text-sm">
{`# Spark: {{timestamp}}

## Summary
{{spark.summary}}

## Evidence
{{#each spark.evidence}}
- {{this}}
{{/each}}

## Dialogue Context
**ARC-0**: {{arc0_contribution}}
**ARC-1**: {{arc1_contribution}}

---
*Generated by ARC v{{version}}*`}
      </pre>

      <hr className="my-12" />

      <h2>Development Roadmap</h2>

      <h3>Phase 1: Local Runtime (Months 1-3)</h3>
      <ul>
        <li>Core ARC-0/ARC-1 dialogue engine</li>
        <li>Local SQLite storage with encryption</li>
        <li>Basic export functionality</li>
        <li>Deterministic prompt system</li>
      </ul>

      <h3>Phase 2: Interface & Experience (Months 4-6)</h3>
      <ul>
        <li>Minimal, contemplative UI</li>
        <li>Spark visualization and history</li>
        <li>Import/export workflow</li>
        <li>Offline-capable web interface</li>
      </ul>

      <h3>Phase 3: Distribution & Community (Months 7-12)</h3>
      <ul>
        <li>P2P sync capabilities</li>
        <li>Plugin architecture for extensions</li>
        <li>Community-contributed prompt libraries</li>
        <li>Mobile contemplation app</li>
      </ul>

      <hr className="my-12" />

      <h2>Contributing Guidelines</h2>

      <h3>Code of Conduct</h3>
      <ul>
        <li><strong>Contemplative development</strong>: Write code that serves reflection, not engagement</li>
        <li><strong>Privacy first</strong>: Every PR must pass privacy review</li>
        <li><strong>Local-first</strong>: All features must work offline</li>
        <li><strong>Calm technology</strong>: No dark patterns, no manipulation tactics</li>
      </ul>

      <h3>Pull Request Process</h3>
      <ol>
        <li><strong>Privacy Impact Assessment</strong>: How does this change affect user data ownership?</li>
        <li><strong>Contemplative Design Review</strong>: Does this serve deep thought or shallow engagement?</li>
        <li><strong>Performance Impact</strong>: How does this affect the mindflow experience?</li>
        <li><strong>Documentation</strong>: All changes must include philosophical context</li>
      </ol>

      <hr className="my-12" />

      <h2>Get Involved</h2>
      <p><strong>Current Status</strong>: Alpha development, seeking thoughtful contributors</p>

      <p><strong>Ways to Contribute</strong>:</p>
      <ul>
        <li><strong>Core Runtime</strong>: Help build the dialogue engine</li>
        <li><strong>UI/UX</strong>: Design interfaces that serve contemplation</li>
        <li><strong>Documentation</strong>: Write guides that honor the philosophy</li>
        <li><strong>Testing</strong>: Ensure privacy and performance standards</li>
        <li><strong>Philosophy</strong>: Help refine the theoretical foundation</li>
      </ul>

      <div className="my-8 text-center">
        <Link
          href="/reach-me"
          className="inline-flex items-center px-8 py-4 bg-accent text-accent-foreground rounded-xl font-medium text-lg hover:bg-accent/90 transition-colors"
        >
          Talk to Founder
        </Link>
        <p className="text-sm text-muted-foreground mt-2">
          Select "Developer/Engineer" role — Response time: 2-3 days
        </p>
      </div>

      <hr className="my-12" />

      <p className="text-sm text-muted-foreground text-center">
        <strong>© 2025 Albira Rahman</strong> — Licensed under ARC-Reflective Use License v1.0<br />
        All code will be released under permissive open-source licenses
      </p>
    </div>
  )
}